[FRED]
api_key = "b80e439e493aa86fbb9f080c3c2600f9"

[REDDIT]
client_id = "ActbsRUTEIPcm0aPMSTqZQ"
client_secret = "69nJvSYIVEcjERqAbwtFW2WTtYZ87w"
user_agent = "macOS:macroscope-fetch:v1.0 (by /u/SavingsMundane368)"